import { GoogleGenAI, Type } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export interface AnalysisResult {
  score: number;
  label: "Human" | "AI" | "Mixed";
  reasoning: string;
  keyIndicators: string[];
  confidence: number;
}

export async function analyzeText(text: string): Promise<AnalysisResult> {
  if (!text || text.trim().length < 10) {
    throw new Error("Text is too short for meaningful analysis.");
  }

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: [
      {
        role: "user",
        parts: [
          {
            text: `Analyze the following text to determine if it was written by a human or generated by an AI. 
            Provide an 'Authenticity Score' (0-100, where 100 is definitely human), a label, a detailed reasoning, 
            and a list of key indicators (linguistic patterns, repetitive structures, etc.).
            
            Text to analyze:
            ---
            ${text}
            ---`,
          },
        ],
      },
    ],
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          score: { type: Type.NUMBER, description: "Authenticity score from 0 to 100" },
          label: { type: Type.STRING, enum: ["Human", "AI", "Mixed"] },
          reasoning: { type: Type.STRING },
          keyIndicators: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
          },
          confidence: { type: Type.NUMBER, description: "Confidence score from 0 to 1" },
        },
        required: ["score", "label", "reasoning", "keyIndicators", "confidence"],
      },
    },
  });

  try {
    return JSON.parse(response.text);
  } catch (error) {
    console.error("Failed to parse Gemini response:", error);
    throw new Error("Failed to analyze text. Please try again.");
  }
}
